export enum ErrorStatus {
    INVALID_USERNAME_OR_USER_CODE = -1,
    INVALID_USER_CODE = -2,
    USER_NOT_FOUND = -3,
    TOO_MANY_USERS = -4,
    INVALID_SONG_NAME_OR_SONG_ID = -5,
    INVALID_SONG_ID = -6,
    SONG_NOT_RECORDED = -7,
    TOO_MANY_RECORDS = -8,
    INVALID_DIFFICULTY = -9,
    INVALID_RECENT_NUMBER = -10,
    ALLOCATE_AN_ARC_ACCOUNT_FAILED = -11,
    CLEAR_FRIEND_FAILED = -12,
    ADD_FRIEND_FAILED = -13,
    THIS_SONG_HAS_NO_BEYOND_LEVEL = -14,
    NOT_PLAYED_YET = -15,
    USER_GOT_SHADOWBANNED = -16,
    QUERYING_BEST30_FAILED = -17,
    UPDATE_SERVICE_UNAVAILABLE = -18,
    INVALID_PARTNER = -19,
    FILE_UNAVAILABLE = -20,
    INTERNAL_ERROR_OCCURRED = -23,
    UNKNOWN_ERROR_OCCURRED = -233
}

const errorStatusString = {
    "en": {
        "-1": "Invalid username or user code",
        "-2": "Invalid user code",
        "-3": "User not found",
        "-4": "Too many users",
        "-5": "Invalid song name or song id",
        "-6": "Invalid song id",
        "-7": "Song not recorded",
        "-8": "Too many records",
        "-9": "Invalid difficulty",
        "-10": "Invalid recent number",
        "-11": "Allocate an Arcaea account failed",
        "-12": "Clear friend list failed",
        "-13": "Add friend failed",
        "-14": "This song has no beyond level",
        "-15": "Not played yet",
        "-16": "User got shadowbanned",
        "-17": "Querying best30 failed",
        "-18": "Update service unavailable",
        "-19": "Invalid partner",
        "-20": "File unavailable",
        "-23": "Internal error occurred",
        "-233": "Unknown error occurred"
    },
    "zh-cn": {
        "-1": "无效的用户名或用户代码",
        "-2": "无效的用户代码",
        "-3": "未找到用户",
        "-4": "匹配到了多个用户",
        "-5": "无效的歌曲名称或歌曲ID",
        "-6": "无效的歌曲ID",
        "-7": "歌曲未记录",
        "-8": "匹配到了多个歌曲条目",
        "-9": "无效的难度",
        "-10": "无效的最近成绩数",
        "-11": "分配Arcaea账号失败",
        "-12": "清空好友列表失败",
        "-13": "添加好友失败",
        "-14": "此歌曲没有Beyond难度",
        "-15": "尚未游玩过",
        "-16": "该用户排行榜已被封禁",
        "-17": "查询Best 30失败",
        "-18": "升级服务不可用",
        "-19": "无效的搭档",
        "-20": "文件不可用",
        "-23": "发生了内部错误",
        "-233": "发生了位置错误"
    },
}

export function errorStatusToString(errorStatus: ErrorStatus, lang: "en" | "zh-cn" = "en") {
    return errorStatusString[lang][errorStatus];
}
